### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by alexgorbatchev** [strongloop/strong-cluster-control#45]
> For full documentation, see **StrongLoop Documentation**.

Leads to http://docs.strongloop.com/display/SLC/Clustering which is a 404

![clustering - operating node applications - documentation 2015-03-18 20-37-34](https://cloud.githubusercontent.com/assets/65633/6724093/b83d06ec-cdae-11e4-9ba0-553a64c8dfe4.png)

**Comment by sam-github** [comment]
Thanks, Alex, fixed in de131060f4b4e

**Comment by alexgorbatchev** [comment]
:+1:
