### ISSUE TITLE
Run-time control of cluster through command line and API?

### ISSUE THREAD

**Issue by alexgorbatchev** [strongloop/strong-cluster-control#46]
`run-time control of cluster through command line and API` is mentioned as a feature but not really described in the doc and after a cursory source scan I don't see this feature. Is this implemented?

**Comment by sam-github** [comment]
Fixed by d03be2d

Implementation was factored out into strongloop/strong-supervisor, and is also exposed as `slc ctl`.

**Comment by sam-github** [comment]
Are you using this module directly? Its simpler to use strong-pm. If you really want to use it directly, and to have the CLI, you can pin to a version earlier than: https://github.com/strongloop/strong-cluster-control/blob/master/CHANGES.md#2014-07-21-version-050

**Comment by alexgorbatchev** [comment]
Writing an article, just shared it with you.
