### ISSUE TITLE
The API docs are not accessible

### ISSUE THREAD

**Issue by grahamlyons** [strongloop/strong-cluster-control#65]
Hi,

I just recommended the `strong-cluster-control` module to a colleague of mine and was derided because the link to your documentation returns a 404:

```
$ curl http://apidocs.strongloop.com/strong-cluster-control/ -D -
HTTP/1.1 404 Not Found
X-Backside-Transport: FAIL FAIL
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/plain
Date: Wed, 05 Apr 2017 08:48:14 GMT
X-Powered-By: Express
X-Vcap-Request-Id: 9cefdbfc-94cf-4a4d-4810-5fb0e340b3c5
X-Client-IP: 80.169.89.58
X-Global-Transaction-ID: 606261279

Cannot GET /strong-cluster-control/
```

Please help to curtail my embarrassment by either making them accessible or removing the link, which promises so much and delivers only crushing disappointment.

Thanks.

**Comment by sam-github** [comment]
Sorry, apidocs now just contains Loopback documentation, not low-level modules like this. But the docs all came from this repo anyhow.

Fixed in a23cfd7
